### ISSUE TITLE
Extension prevents posting updates on a thread that is under the age limit

### ISSUE THREAD

**Issue by ExZiByte** [FriendsOfFlarum/prevent-necrobumping#3]
When I activate the extension and input the settings how I would like it to work. I have it set to warn after 30 days, but when I try to post on a thread that is 3 days old, the extension just says "This discussion is too old to reply to.". The thread I am posting on did exist prior to activating the extension so that could be the cause.

**Comment by dsevillamartin** [comment]
Hm... it shouldn't matter if the discussion existed before enabling the discussion or not. Perhaps the server logic that validates the age is incorrect. Does the yellow warning message appear when replying to the discussion?

**Comment by ExZiByte** [comment]
No it only shows this in the bottom right of the screen
![image](https://user-images.githubusercontent.com/22984994/52918373-cb254000-32bb-11e9-860d-04e2b61dc1d3.png)

**Comment by dsevillamartin** [comment]
Then it is a bug with the server verification. Not sure what could cause 27 days to be ignored 🤔

**Comment by luceos** [comment]
Looking at the Listener, it will automatically run the `accepted` validation whenever the last posted at is at least one day old. The configuration isn't even used, see:

https://github.com/FriendsOfFlarum/prevent-necrobumping/blob/9fa0b5b6d16790014e31cfbbec898983e805f48c/src/Listeners/ValidateNecrobumping.php#L36-L40

**Comment by dsevillamartin** [comment]
@luceos Seems like I did an Oops! while writing that code. Will look into it, thanks

**Comment by luceos** [comment]
Wanted to pr it. But didn't get the chance yet, sorry.
